### ISSUE TITLE
Error updating

### ISSUE THREAD

**Issue by dsisnero** [ruby-rdf/rdf-trig#1]
C:\Users\Dominic E Sisneros>gem update
Updating installed gems
Updating rdf-trig
ERROR:  Error installing rdf-trig:
        conflicting dependencies ebnf (~> 2.0) and ebnf (~> 1.2)
  Activated ebnf-1.2.0
  which does not match conflicting dependency (~> 2.0)

  Conflicting dependency chains:
    rdf-trig (= 3.1.1), 3.1.1 activated, depends on
    rdf-turtle (~> 3.1), 3.1.0 activated, depends on
    ebnf (~> 1.2), 1.2.0 activated

  versus:
    rdf-trig (= 3.1.1), 3.1.1 activated, depends on
    ebnf (~> 2.0)

Updating sorbet
ERROR:  Error installing sorbet:
        Unable to resolve dependency: No match for 'sorbet-static (= 0.5.5843)' on this platform. Found: java, universal-darwin-14, universal-darwin-15, universal-darwin-16, universal-darwin-17, universal-darwin-18, universal-darwin-19, x86_64-linux
Nothing to update

**Comment by gkellogg** [comment]
I’ll push out a new version with updated dependencies

**Comment by gkellogg** [comment]
I needed to release rdf-turtle 3.1.2 to have similar dependencies. Try updating and trying again.
